# 这个文件的名字可以随便起，但必须放在 .github/workflows/ 目录下
name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"] # 只要你向 main 分支推送代码，机器人就开工
  workflow_dispatch:   # 允许你在 Actions 页面手动点击运行

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Download Theme
        run: |
          mkdir -p themes/blowfish
          curl -L https://github.com/nunocoracao/blowfish/archive/refs/tags/v2.100.0.tar.gz | tar -xz --strip-components=1 -C themes/blowfish

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.157.0' # 总是使用最新的 Hugo 版本
          extended: true         # 必须开启，因为酷炫主题通常需要 Extended 版本

      - name: Build
        run: hugo --minify      # 让 Hugo 开始构建你的网站，并压缩文件

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public         # 告诉机器人：构建好的网页就在 public 文件夹里

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # 正式发布到互联网
